### ISSUE TITLE
The box 'phusion/ubuntu-14.04-amd64' could not be found

### ISSUE THREAD

**Issue by fernandodbc** [Cethy/vagrant-gaudi#1]
Hello,

I made a : vagrant up
But the box 'phusion/ubuntu-14.04-amd64' could not be found....

What is the curent box to use ?

Regards

**Comment by Cethy** [comment]
You might need to make a `vagrant init phusion/ubuntu-14.04-amd64` before `vagrant up` ;
Otherwise, you can find the box in this project : https://github.com/phusion/open-vagrant-boxes
